/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sharma1
 */
public class Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelContrasenia = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jTxtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTituloIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        getContentPane().setLayout(null);

        jLabelContrasenia.setText("Contraseña");
        getContentPane().add(jLabelContrasenia);
        jLabelContrasenia.setBounds(210, 220, 70, 30);

        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtUsuario);
        jTxtUsuario.setBounds(310, 160, 150, 30);
        getContentPane().add(jTxtContrasenia);
        jTxtContrasenia.setBounds(310, 220, 150, 30);

        btnIngresar.setBackground(new java.awt.Color(51, 51, 255));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(310, 290, 90, 40);
        getContentPane().add(label);
        label.setBounds(150, 390, 0, 0);

        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(210, 160, 70, 30);

        jLabelTituloIngresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloIngresar.setText("Ventana de Ingreso");
        getContentPane().add(jLabelTituloIngresar);
        jLabelTituloIngresar.setBounds(290, 90, 190, 30);

        setSize(new java.awt.Dimension(715, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from createuser where username=? and password=?";//usertable
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jTxtUsuario.getText());
                mystatement.setString(2, jTxtContrasenia.getText());
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    if (myresult.getString("usertype").equals("Admin")) {
                        Marco1 obj = new Marco1();
                        obj.setVisible(true);
                        this.setVisible(false);
                    } else if (myresult.getString("usertype").equals("Manager")) {
                        Marco11 obj = new Marco11();
                        obj.setVisible(true);
                        this.setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Wrong Password/Username");
                }
                
                mystatement.close();
                myconnection.close();
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelTituloIngresar;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jTxtContrasenia;
    private javax.swing.JTextField jTxtUsuario;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
