
package ProyectoConcurrente;

import java.sql.*;
import javax.swing.JOptionPane;
public class Tienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Company
     */
    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTxtTituloAgregarProveedor = new javax.swing.JLabel();
        jTxtNombreProveedor = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Companía");
        getContentPane().setLayout(null);

        jTxtTituloAgregarProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTituloAgregarProveedor.setText("Agregar Proveedor");
        getContentPane().add(jTxtTituloAgregarProveedor);
        jTxtTituloAgregarProveedor.setBounds(70, 20, 180, 30);

        jTxtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNombreProveedor);
        jTxtNombreProveedor.setBounds(40, 70, 230, 30);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(90, 130, 110, 30);

        setBounds(0, 0, 314, 227);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreProveedorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String path="jdbc:mysql://localhost/";
        String place="factorydb";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection= DriverManager.getConnection(path+place,"root","");
            try
            {
                String q="insert into Company values(?)";
                PreparedStatement mystatement =myconnection.prepareStatement(q);
                mystatement.setString(1, jTxtNombreProveedor.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
                jTxtNombreProveedor.setText(null);

                mystatement.close();
                myconnection.close();

            }
            catch(Exception ae)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query" + ae.getMessage());
            }
        }
        catch(Exception ae)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTxtNombreProveedor;
    private javax.swing.JLabel jTxtTituloAgregarProveedor;
    // End of variables declaration//GEN-END:variables
}
